### ISSUE TITLE
Pull a specific file / folder

### ISSUE THREAD

**Issue by olaurendeau** [openl10n/openl10n-cli#37]
First of all thanks a lot for this awesome project. I've been thinking about something like openl10n for a long time.

As openl10n.phar allow to push a specific file, I think that it make sense to be able to pull a specific file / folder.
We have been able to bypass this by creating various configuration files. But it's not really reliable.

If you validate this feature, we will try to implement it. :)

**Comment by MattKetmo** [comment]
Yes sure, it should be quite easy to do btw.

May I ask what your motivation for this feature? Is it for performance reason or more because of your dev workflow (eg. you don't want to pull translations that you're not responsible for)?

**Comment by olaurendeau** [comment]
It's for our development workflow. On our backoffice project we can have 3 or 4 teams working on the project but on different domains. So we should be able to avoid most of conflicts with a file precision.
