### ISSUE TITLE
The "working-dir" option does not exist.

### ISSUE THREAD

**Issue by jdeniau** [openl10n/openl10n-cli#46]
When installling on a directory-level, I got this error.

I think you can reproduce it like this:

``` sh
mkdir test;
cd test;
composer require openl10n/cli;
vendor/openl10n/cli/bin/openl10n init;
```

The `pull` command does not work either when in a openl10n-managed directory

**Comment by MeuhMeuh** [comment]
Any update guys ?

**Comment by GaelleG** [comment]
+1

**Comment by FlorianBaba** [comment]
+1
